http://pisaruk.narod.ru/slides/games/nonCoop.pdf (слайд 133, игра "Проклятие общего")

http://om.univ.kiev.ua/users_upload/5/upload/file/2016_mmoti_semenov.pdf - экстраградиентный метод

https://web.stanford.edu/class/ee364b/lectures/monotone_slides.pdf - Monotone Operators

$F(\mathbf{x}) = \mathbf{x} + (\mathbf{1}^T\mathbf{x})\mathbf{1} - \mathbf{1} = (\mathbf{I} + \mathbf{E})\mathbf{x} - \mathbf{1}$

[Константа Липшица](https://ru.wikipedia.org/wiki/%D0%9B%D0%B8%D0%BF%D1%88%D0%B8%D1%86%D0%B5%D0%B2%D0%BE_%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5):

$$L = \max_{\mathbf{x},\mathbf{y}} \frac{\|F(\mathbf{x}) - F(\mathbf{y})\|}{\|\mathbf{x} - \mathbf{y}\|} = \max_{\mathbf{x},\mathbf{y}} \frac{\| \mathbf{x} - \mathbf{y} + \mathbf{1}\mathbf{1}^T(\mathbf{x} - \mathbf{y}) \|}{\|\mathbf{x} - \mathbf{y}\|}$$

Обозначая $\mathbf{d} = \mathbf{x} - \mathbf{y}$ и предполагая, что $d_1 = d_2 = ... = d_N$, получаем что $L = N+1$.

In [1]:
import numpy as np

In [2]:
class Operator:
    def __init__(self, F, Lconstant):
        self.F = F
        self.Lipschitz_constant = Lconstant
    def __call__(self, x):
        return self.F(x)
    def lipschitz_constant(self):
        return self.Lipschitz_constant
    

In [3]:
def F(x):
    return x + np.sum(x) - 1

N = 7

Lconstant = N+1

F = Operator(F, Lconstant)

In [4]:
from numpy.linalg import norm

def extragradient(F, x0, proj=lambda x: x):
    max_iter = 1000000
    alpha = 1./(F.lipschitz_constant() + 1e-2)
    x = x0.copy()
    is_converged = False
    for k in range(max_iter):
        z = proj(x - alpha*F(x))
        x = proj(x - alpha*F(z))
        if norm(x-z)/norm(x) < 1e-8:
            is_converged = True
            break
    if is_converged:
        print('Converged!')
    else:
        print('Not converged!')
    return x
    

In [5]:
x0 = np.random.rand(N,)
x_sol = extragradient(F, x0, proj=lambda x: np.clip(x, 0, 1))
print(x_sol)

Converged!
[0.125 0.125 0.125 0.125 0.125 0.125 0.125]


In [6]:
from numpy.linalg import solve

x_sol_analytic = solve(np.eye(N) + np.ones((N,N)), np.ones((N,)))
print(x_sol_analytic)

[0.125 0.125 0.125 0.125 0.125 0.125 0.125]


In [7]:
x_sol_analytic = np.ones((N))/(N+1)
print(x_sol_analytic)

[0.125 0.125 0.125 0.125 0.125 0.125 0.125]
